language: python
sudo: require
python:
  - "2.7"
  - "3.5"
  - "3.6"

matrix:
  include:
    - language: generic
      os: osx
      python: 2.7.13
    - language: generic
      os: osx
      python: 3.5.4
    - language: generic
      os: osx
      python: 3.6.4

addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran

before_install:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew update
    if  [ "${PYTHON:0:1}" = "3" ]; then
      brew upgrade python
      brew install python3
    fi
    sudo chown -R $USER /Library/Python/2.7
    sudo easy_install pip
  fi

install:
  - travis_wait travis_retry sudo pip install -r requirements.txt --ignore-installed flake8 isort cpplint annoy
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis_retry sudo chown -R $USER /Library/Python/2.7; fi
  - travis_retry python setup.py build install

script:
  - flake8
  - flake8 --filename='*.pyx,*.px*' --ignore E901,E225,E226,E227,E999
  - isort -c **/*.py
  - cpplint --linelength 100 **/*.h
  - python setup.py test

cache:
  - apt
  - directories:
    - $HOME/.cache/pip
